# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*' # 触发条件：推送以 v 开头的标签，如 v1.0.0

# 添加权限配置
permissions:
  contents: write
  discussions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install build

      - name: Build package
        run: |
          python -m build
          echo "Checking dist directory contents:"
          ls -la dist/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          draft: false
          prerelease: false
          generate_release_notes: true

      # 可选：如果你想自动更新 Homebrew Formula
      - name: Get SHA256
        id: shasum
        run: |
          echo "Checking dist directory contents:"
          ls -la dist/
          TARBALL_PATH=$(ls dist/*.tar.gz | head -n 1)
          echo "Found tarball: $TARBALL_PATH"
          echo "sha=$(sha256sum $TARBALL_PATH | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      # 如果你有独立的 homebrew-tools 仓库，可以自动更新 Formula
      - name: Update Homebrew Formula
        if: steps.shasum.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Setting up git configuration..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "Cloning repository..."
          git clone "https://oauth2:${GITHUB_TOKEN}@github.com/markshawn2020/homebrew-tools.git"
          
          cd homebrew-tools
          
          echo "Updating formula..."
          if [ ! -f "Formula/md-dlp.rb" ]; then
            echo "Error: Formula file not found"
            exit 1
          fi
          
          # Update version and sha256
          VERSION="${{ github.ref_name }}"
          VERSION_WITHOUT_V="${VERSION#v}"
          sed -i "s|url \".*\"|url \"https://github.com/markshawn2020/md-dlp/archive/${VERSION}.tar.gz\"|" Formula/md-dlp.rb
          sed -i "s/sha256 \".*\"/sha256 \"${{ steps.shasum.outputs.sha }}\"/" Formula/md-dlp.rb
          
          echo "Committing changes..."
          git add Formula/md-dlp.rb
          git commit -m "Update md-dlp to ${{ github.ref_name }}"
          
          echo "Pushing changes..."
          git push